package:
  name: ndtomo
  version: "2025.02"
source:
  path: .
channels:
  - conda-forge
  - anaconda
  - astra-toolbox/label/dev
requirements:
  build:
    - python
    - pip
  run:
    - python
    - pyfai
    - fabio
    - silx
    - tqdm 
    - h5py
    - ipython
    - nb_conda_kernels 
    - scikit-image 
    - scikit-learn
    - pyopencl 
    - numpy
    - matplotlib
    - scipy
    - mayavi
    - napari
    - jupyterlab
    - tifffile 
    - pillow 
    - algotom 
    - astra-toolbox
    - pystackreg
  script: python setup.py install --single-version-externally-managed --record=record.txt
about:
  home: https://github.com/antonyvam/nDTomo
  summary: "nDTomo software suite"
  license: General Public License v3.0
  dev_url: https://github.com/antonyvam/nDTomo
  doc_url: https://ndtomo.readthedocs.io
extra:
  maintainers:
   - antonyvam