{% set name = "ndtomo" %}
{% set version = "2022.03" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"
source:
  path: .
requirements:
  build:
    - python>3.8
  run:
    - python
channels:
  - astra-toolbox/label/dev
  - conda-forge
  - anaconda
dependencies:
  - astra-toolbox
  - tomopy
  - ase
  - fabio
  - h5py
  - periodictable
  - pyfai=0.19.0
  - silx
  - pyqtgraph
  - tifffile
  - scikit-image
  - scikit-learn
  - scipy
  - tqdm
  - ipython
  - matplotlib
  - jupyterlab
  - spyder
  - pystackreg 
  - xdesign 
  - cached_property 
  - pymcr 

