# -*- coding: utf-8 -*-
#
# Configuration file for the Sphinx documentation builder.
#
# This file does only contain a selection of the most common options. For a
# full list see the documentation:
# http://www.sphinx-doc.org/en/master/config

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os, sys, shutil

sys.path.insert(0, os.path.abspath('../..'))
sys.setrecursionlimit(1500)

notebooks_src = os.path.abspath("./notebooks/")
notebooks_dest = os.path.abspath("./_build/html/notebooks/")

if os.path.exists(notebooks_src):
    if not os.path.exists(notebooks_dest):
        shutil.copytree(notebooks_src, notebooks_dest)

sys.path.insert(0, os.path.abspath("../../nDTomo")) 
		
# -- Project information -----------------------------------------------------

project = u'nDTomo'
copyright = u'2019, A. Vamvakeros'
author = u'A. Vamvakeros'

# The short X.Y version
version = u''
# The full version, including alpha/beta/rc tags
release = u'2025.01'


# -- General configuration ---------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
	'nbsphinx', # Enables Jupyter notebooks in Sphinx
	'sphinx.ext.mathjax',  # Enables LaTeX rendering
    'sphinx.ext.autodoc',
    'sphinx.ext.intersphinx',
    'sphinx.ext.ifconfig',
    'sphinx.ext.viewcode',
    'sphinx.ext.napoleon',  # For Google/NumPy style docstrings	
    'sphinx.ext.githubpages',
	'sphinx.ext.autosummary',
]
nbsphinx_allow_errors = True
autosummary_generate = True  # Auto-generate function/method summary

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = "en"

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = []

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = None


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'sphinx_rtd_theme'

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
# html_theme_options = {}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# The default sidebars (for documents that don't match any pattern) are
# defined by theme itself.  Builtin themes are using these templates by
# default: ``['localtoc.html', 'relations.html', 'sourcelink.html',
# 'searchbox.html']``.
#
# html_sidebars = {}


# -- Options for HTMLHelp output ---------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'nDTomodoc'


# -- Options for LaTeX output ------------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',

    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',

    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',

    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, 'nDTomo.tex', u'nDTomo Documentation',
     u'A. Vamvakeros', 'manual'),
]


# -- Options for manual page output ------------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, 'ndtomo', u'nDTomo Documentation',
     [author], 1)
]


# -- Options for Texinfo output ----------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'nDTomo', u'nDTomo Documentation',
     author, 'nDTomo', 'One line description of project.',
     'Miscellaneous'),
]


# -- Options for Epub output -------------------------------------------------

# Bibliographic Dublin Core info.
epub_title = project

# The unique identifier of the text. This can be a ISBN number
# or the project homepage.
#
# epub_identifier = ''

# A unique identification for the text.
#
# epub_uid = ''

# A list of files that should not be packed into the epub file.
epub_exclude_files = ['search.html']


# -- Extension configuration -------------------------------------------------

# -- Options for intersphinx extension ---------------------------------------

# Example configuration for intersphinx: refer to the Python standard library.
intersphinx_mapping = {'python': ('https://docs.python.org/3/', None)}


nbsphinx_prolog = r"""
.. raw:: html

    <style>
        div.nbinput.hide-input {
            display: none;
        }
    </style>
"""

latex_engine = 'pdflatex'  # or xelatex/lualatex
latex_documents = [
    ('index', 'nDTomo.tex', 'nDTomo Documentation',
     'Antonis Vamvakeros et al.', 'manual'),
]

latex_elements = {
    'inputenc': '',  # use utf8
    'utf8extra': '',
    'preamble': r'''
\usepackage[utf8]{inputenc}
\DeclareUnicodeCharacter{03C0}{$\pi$}
\DeclareUnicodeCharacter{2588}{\rule{0.5em}{0.5em}}
\DeclareUnicodeCharacter{1F50D}{\textbf{[Search]}}
\DeclareUnicodeCharacter{1F9F1}{\textbf{[Brick]}}
\DeclareUnicodeCharacter{1F9E0}{\textbf{[Brain]}}
\DeclareUnicodeCharacter{1F9F0}{\textbf{[Toolbox]}}
\DeclareUnicodeCharacter{26A0}{\textbf{[Warning]}}
\DeclareUnicodeCharacter{1F501}{\textbf{[Repeat]}}
\DeclareUnicodeCharacter{2699}{\textbf{[Gear]}}
\DeclareUnicodeCharacter{2705}{\textbf{[Check]}}
\DeclareUnicodeCharacter{1F5BC}{\textbf{[Image]}}
\DeclareUnicodeCharacter{1F4C8}{\textbf{[Chart]}}
\DeclareUnicodeCharacter{1F4CA}{\textbf{[Graph]}}
\DeclareUnicodeCharacter{1F4CB}{\textbf{[Clipboard]}}
\DeclareUnicodeCharacter{1F6E0}{\textbf{[Wrench]}}
\DeclareUnicodeCharacter{1F680}{\textbf{[Rocket]}}
\DeclareUnicodeCharacter{1F4A1}{\textbf{[Idea]}}
\DeclareUnicodeCharacter{1F4D6}{\textbf{[Book]}}
\DeclareUnicodeCharacter{1F3A8}{\textbf{[Art]}}
\DeclareUnicodeCharacter{1F527}{\textbf{[Spanner]}}
\DeclareUnicodeCharacter{1F52C}{\textbf{[Microscope]}}
\DeclareUnicodeCharacter{1F393}{\textbf{[Graduate]}}
\DeclareUnicodeCharacter{1F9EE}{\textbf{[Clipboard]}}
\DeclareUnicodeCharacter{1F916}{\textbf{[Robot]}}
\DeclareUnicodeCharacter{1F4AC}{\textbf{[Speech]}}
%% Block characters
\DeclareUnicodeCharacter{2588}{\rule{0.5em}{0.5em}}  %% █
\DeclareUnicodeCharacter{2593}{\rule{0.4em}{0.4em}}  %% ▓
\DeclareUnicodeCharacter{2592}{\rule{0.3em}{0.3em}}  %% ▒
\DeclareUnicodeCharacter{25A0}{\rule{0.5em}{0.5em}}  %% ■

%% Math / Greek
\DeclareUnicodeCharacter{03C0}{\ensuremath{\pi}}      %% π
\DeclareUnicodeCharacter{03B1}{\ensuremath{\alpha}}   %% α
\DeclareUnicodeCharacter{03B2}{\ensuremath{\beta}}    %% β
\DeclareUnicodeCharacter{03B3}{\ensuremath{\gamma}}   %% γ
\DeclareUnicodeCharacter{03B4}{\ensuremath{\delta}}   %% δ
\DeclareUnicodeCharacter{03B8}{\ensuremath{\theta}}   %% θ
\DeclareUnicodeCharacter{03BC}{\ensuremath{\mu}}      %% μ
\DeclareUnicodeCharacter{03C3}{\ensuremath{\sigma}}   %% σ
\DeclareUnicodeCharacter{03C9}{\ensuremath{\omega}}   %% ω

%% Arrows
\DeclareUnicodeCharacter{2192}{\textrightarrow}       %% →
\DeclareUnicodeCharacter{2190}{\textleftarrow}        %% ←
\DeclareUnicodeCharacter{2191}{\textuparrow}          %% ↑
\DeclareUnicodeCharacter{2193}{\textdownarrow}        %% ↓
\DeclareUnicodeCharacter{21D2}{\Rightarrow}           %% ⇒
\DeclareUnicodeCharacter{21D0}{\Leftarrow}            %% ⇐

%% Box and logic
\DeclareUnicodeCharacter{25B6}{\textbf{[▶]}}           %% ▶
\DeclareUnicodeCharacter{25CB}{\textbf{(o)}}           %% ○
\DeclareUnicodeCharacter{25CF}{\textbullet}            %% ●

%% Emojis & Icons
\DeclareUnicodeCharacter{1F50D}{\textbf{[Search]}}     %% 🔍
\DeclareUnicodeCharacter{1F52C}{\textbf{[Microscope]}} %% 🔬
\DeclareUnicodeCharacter{1F9E0}{\textbf{[Brain]}}      %% 🧠
\DeclareUnicodeCharacter{1F9F1}{\textbf{[Brick]}}      %% 🧱
\DeclareUnicodeCharacter{1F9F0}{\textbf{[Toolbox]}}    %% 🧰
\DeclareUnicodeCharacter{1F501}{\textbf{[Repeat]}}     %% 🔁
\DeclareUnicodeCharacter{1F4A1}{\textbf{[Idea]}}       %% 💡
\DeclareUnicodeCharacter{1F4CA}{\textbf{[Chart]}}      %% 📊
\DeclareUnicodeCharacter{1F5BC}{\textbf{[Image]}}      %% 🖼
\DeclareUnicodeCharacter{2705}{\textbf{[Check]}}       %% ✅
\DeclareUnicodeCharacter{26A0}{\textbf{[Warning]}}     %% ⚠
\DeclareUnicodeCharacter{2699}{\textbf{[Gear]}}        %% ⚙
\DeclareUnicodeCharacter{231B}{\textbf{[Hourglass]}}   %% ⌛

%% Misc
\DeclareUnicodeCharacter{2022}{\textbullet}            %% •
\DeclareUnicodeCharacter{2212}{-}                      %% − (minus sign)
\DeclareUnicodeCharacter{00A0}{~}                      %% Non-breaking space
\DeclareUnicodeCharacter{FE0F}{}                       %% VARIATION SELECTOR-16 (invisible)
\DeclareUnicodeCharacter{200D}{}                       %% ZERO WIDTH JOINER (invisible)
\DeclareUnicodeCharacter{FE0F}{}
\DeclareUnicodeCharacter{274C}{}
'''
}
