
# Block 0
def id15_user_mac '{
	# Block 1
	euro2400parameters unit=3 RampRate=20 
	local qq 
	qq = 0 
	umv euro0 85.000000 ; ct 1 
	while( S[euro0pv] < (850-50) ) {

		# Block 2
		fileName = sprintf("pox_rampR_map_%.4d", qq)
		cmd = sprintf("xrdmap %s 6.000000 0.040000 0.050000 0.000000 -5.500000 0.500000", fileName)
		eval(cmd)

		# update while loop parameters
		ct 1 ; sleep(10)
	
		qq++
	}
}'
