
# Block 0
def id15_user_mac '{
	# Block 1
	fileName = "prefix_zscan"
	cmd = sprintf("xrd_zscan %s 20.000000 0.000000 1.000000 0.100000", fileName)
	eval(cmd)

	# Block 2
	local qq
	for (qq=0; qq<5; qq++) {
		# Block 3
		umvr aerox 20.000000
		# Block 4
		fileName = sprintf("prefix_%.4d", qq)
		cmd = sprintf("xrd_point_norot %s 250", fileName)
		eval(cmd)

		# Block 5
		umvr hrz 1.000000
		# Block 6
		fileName = sprintf("prefix_aeroyScan_%.4d", qq)
		cmd = sprintf("xrdmap %s 0.000000 2.000000 0.100000 0.020000", fileName)
		eval(cmd)

	}
	# Block 7
	umvr hrz 1.000000
	# Block 8
	local pp 
	pp = 0 
	t0 = time() ; t = time() 
	while ( (t-t0) < 600 ) {
		# Block 9
		p "Sleeping ..."
		sleep(10)

		# Block 10
		fileName = sprintf("prefix_xrdct_%.4d", pp)
		cmd = sprintf("xrdct3d %s 3.000000 2.000000 0.050000 0.020000", fileName)
		eval(cmd)

		# update while loop parameters
		pp++ ; t = time()
	}
	# Block 11
	fileName = "prefix_map"
	cmd = sprintf("xrdmap %s 0.000000 2.000000 0.050000 0.020000 0.000000 1.000000 0.100000", fileName)
	eval(cmd)

}'
