name: ndtomo-docs
channels:
  - conda-forge
  - defaults
  - astra-toolbox/label/dev
dependencies:
  - python=3.9
  - pip
  - sphinx
  - sphinx-rtd-theme
  - nbsphinx
  - sphinx-autodoc-typehints
  - pyfai
  - fabio
  - pip:
    - sphinx
    - sphinx-rtd-theme
    - nbsphinx
    - sphinx-autodoc-typehints