name: ndtomo
channels:
  - defaults
dependencies:
  - python=3.9
  - astra-toolbox
  - pip
  - pip:
      --index-url https://download.pytorch.org/whl/cpu    
      - git+https://github.com/antonyvam/nDTomo.git  
      - torch
      - torchvision
      - torchaudio
