channels:
  - astra-toolbox
  - conda-forge
dependencies:
  - python=3.11
  - astra-toolbox
  - jupyterlab
  - h5py
  - matplotlib
  - numpy
  - scipy
  - scikit-image
  - scikit-learn
  - tqdm
  - ipykernel
  - tifffile
  - pyFAI>=2025.01
  - napari
  - configobj
  - ipympl
  - jupyterlab_widgets
  - xgboost
  - pip
  - pip:
      - pyqt5
      - siphash24
      - pyqtgraph
      - xdesign
      - pystackreg
      - algotom
      - fabio
      - torch --index-url https://download.pytorch.org/whl/cpu
      - torchvision --index-url https://download.pytorch.org/whl/cpu