# This workflow will upload a Python Package to PyPI when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package to PyPI

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  release-build:
    name: Build distribution files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install packaging tools
        run: |
          python -m pip install --upgrade pip
          python -m pip install build
      
      # Overwrites __version__ with exact GitHub Release tag string
      - name: Inject Release Version into __init__.py
        run: |
          VERSION="${{ github.event.release.tag_name }}"
          # Removes leading 'v' if your tag is named 'v2026.07' instead of '2026.07'
          VERSION="${VERSION#v}" 
          echo "__version__ = '$VERSION'" > nDTomo/__init__.py
          
      - name: Build release distributions
        run: |
          python -m build

      - name: Upload distributions artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/

  pypi-publish:
    name: Publish to PyPI via Trusted Publishing
    runs-on: ubuntu-latest
    needs:
      - release-build
    permissions:
      id-token: write

    environment:
      name: pypi
      url: https://pypi.org/project/nDTomo/

    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
