name: Publish to Zenodo

on:
  release:
    types:
      - published  # Trigger when a new release is published

jobs:
  publish_to_zenodo:
    runs-on: ubuntu-latest

    steps:
    - name: Test Zenodo API Key
      run: |
        echo "Testing Zenodo API key..."
        response=$(curl -H "Authorization: Bearer ${{ secrets.ZENODO_API_TOKEN }}" \
                     https://zenodo.org/api/deposit/depositions)
        echo "Response from Zenodo API:"
        echo $response
